apiVersion: v2
version: 4.1.0
name: openebs
appVersion: 4.1.0
description: Containerized Attached Storage for Kubernetes
icon: https://raw.githubusercontent.com/cncf/artwork/HEAD/projects/openebs/icon/color/openebs-icon-color.png
home: https://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - local-storage
  - NVMe
  - storage
  - kubernetes
sources:
  - https://github.com/openebs/openebs
dependencies:
  - name: openebs-crds
    version: 4.1.0
  - name: localpv-provisioner
    version: 4.1.0
    repository: "https://openebs.github.io/dynamic-localpv-provisioner"
  - name: zfs-localpv
    version: 2.6.0
    repository: "https://openebs.github.io/zfs-localpv"
    condition: engines.local.zfs.enabled
  - name: lvm-localpv
    version: 1.6.0
    repository: "https://openebs.github.io/lvm-localpv"
    condition: engines.local.lvm.enabled
  - name: mayastor
    version: 2.7.0
    repository: "https://openebs.github.io/mayastor-extensions"
    condition: engines.replicated.mayastor.enabled
  - name: velero
    version: 6.7.0
    repository: "https://vmware-tanzu.github.io/helm-charts"
    condition: backup-restore.enabled
